name: PR Review Reminder to Google Chat

on:
  schedule:
    - cron: "0 13 * * *"  # Daily at 13:00 UTC (adjust as needed)
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get open PRs needing review
        id: prs
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const filtered = prs.data.filter(pr => pr.requested_reviewers.length > 0);
            return filtered.map(pr => ({
              number: pr.number,
              title: pr.title,
              url: pr.html_url,
              reviewers: pr.requested_reviewers.map(r => r.login)
            }));

      - name: Send reminder to Google Chat
        if: steps.prs.outputs.result != '[]'
        uses: google-github-actions/send-google-chat-webhook@v0.0.4
        with:
          webhook_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          payload: |
            {
              "text": "*Daily Review Reminder*\n${{ steps.prs.outputs.result }}"
            }
      - name: No pending PRs
        if: steps.prs.outputs.result == '[]'
        uses: google-github-actions/send-google-chat-webhook@v0.0.4
        with:
          webhook_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          payload: '{"text": "✅ No PRs awaiting review today!"}'
